---
datasource:
  password: lishenming
  test:
    url: "jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8"
  test2:
    url: "jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=UTF-8"
  username: lishenming
logging:
  config: "classpath:log4j2_dev.xml"
server:
  session:
    timeout: 30
spring:
  # mail 的相关配置
  mail:
    host: smtp.126.com
    # 授权码是用于登录第三方邮件客户端的专用密码
    password: 920116li
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: lishenming8@126.com
  # rabbitmq 的相关配置
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  # redis 的相关配置
  redis:
    host: "127.0.0.1"
    password: my_password
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 0
