datasource:
  password: lishenming
  test:
    url: "jdbc:mysql://192.168.31.80:3306/test?characterEncoding=UTF-8"
  username: lishenming
logging:
  config: "classpath:log4j2_dev.xml"
server:
  session:
    timeout: 30